foreground = yes
pid =
setuid = stunnel4
setgid = stunnel4
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
sslVersionMin = TLSv1.2
options = NO_SSLv2
options = NO_SSLv3
TIMEOUTidle = 7200

[zigcho-irc]
accept = 0.0.0.0:6697
connect = 127.0.0.1:16667
cert = /etc/stunnel/zigcho-irc.pem
