FROM rust@sha256:4ec71e955e6c08aeb238885083222ddff79d82eb87654a96c76e38e94da1a53b

ARG ZIG_VERSION=0.16.0
ARG ZIG_SHA256=70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl libpq-dev libsqlite3-dev pkg-config xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN curl --fail --location --silent --show-error \
        "https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz" \
        --output /tmp/zig.tar.xz \
    && echo "${ZIG_SHA256}  /tmp/zig.tar.xz" | sha256sum --check --strict \
    && mkdir /opt/zig \
    && tar --extract --xz --file /tmp/zig.tar.xz --strip-components=1 --directory /opt/zig \
    && ln -s /opt/zig/zig /usr/local/bin/zig \
    && rm /tmp/zig.tar.xz

WORKDIR /src
COPY . .

RUN zig build test \
    && zig build -Doptimize=ReleaseSafe \
    && zig build -Dpostgres=true -Doptimize=ReleaseSafe \
    && mkdir /out \
    && cp zig-out/bin/zigcho zig-out/bin/zigcho-import zig-out/bin/zigcho-import-archive zig-out/bin/zigcho-migrate-postgres /out/
