[package]
name = "zigcho-pp"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
akatsuki-pp = { git = "https://github.com/osuAkatsuki/akatsuki-pp-rs" }
rosu-map = "=0.2.0"

[profile.release]
codegen-units = 16
lto = "off"
panic = "unwind"
strip = "debuginfo"
