name = zigcho-kai
server_name = kai.ovh
root = /opt/zigcho/public
index = index.html
serve_static_root = false
proxy = http://127.0.0.1:27180
upstream_policy = round_robin
php_info_page = false
tls_cert = /etc/letsencrypt/live/kai.ovh/fullchain.pem
tls_key = /etc/letsencrypt/live/kai.ovh/privkey.pem
