BEGIN;

CREATE TABLE zigcho.lazer_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentable_type text NOT NULL CHECK(commentable_type IN ('beatmapset','build','news_post')),
    commentable_id bigint NOT NULL CHECK(commentable_id > 0),
    user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    parent_id bigint REFERENCES zigcho.lazer_comments(id) ON DELETE CASCADE,
    message text NOT NULL CHECK(length(message) BETWEEN 0 AND 1000),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    deleted_at bigint,
    CHECK(parent_id IS NULL OR parent_id != id)
);
CREATE INDEX lazer_comments_target ON zigcho.lazer_comments(commentable_type,commentable_id,parent_id,created_at,id);
CREATE TABLE zigcho.lazer_comment_votes (
    comment_id bigint NOT NULL REFERENCES zigcho.lazer_comments(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(comment_id,user_id)
);
CREATE TABLE zigcho.lazer_comment_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES zigcho.lazer_comments(id) ON DELETE CASCADE,
    reporter_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 64),
    comments text NOT NULL CHECK(length(comments) <= 1000),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE UNIQUE INDEX lazer_comment_reports_once ON zigcho.lazer_comment_reports(comment_id,reporter_id);

INSERT INTO zigcho.schema_migrations(version) VALUES(32);
COMMIT;
