BEGIN;

ALTER TABLE zigcho.users ADD COLUMN username_changes integer NOT NULL DEFAULT 0 CHECK(username_changes>=0);
ALTER TABLE zigcho.users ADD COLUMN username_changed_at bigint;

CREATE TABLE zigcho.user_name_changes(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    old_name text NOT NULL,
    new_name text NOT NULL,
    changed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX user_name_changes_user_time ON zigcho.user_name_changes(user_id,changed_at DESC,id DESC);

CREATE TABLE zigcho.user_banners(
    user_id integer PRIMARY KEY REFERENCES zigcho.users(id) ON DELETE CASCADE,
    object_key text NOT NULL UNIQUE CHECK(length(object_key) BETWEEN 1 AND 200),
    content_type text NOT NULL CHECK(content_type IN('image/png','image/jpeg','image/gif')),
    etag char(64) NOT NULL,
    width integer NOT NULL CHECK(width BETWEEN 1 AND 2000),
    height integer NOT NULL CHECK(height BETWEEN 1 AND 500),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE zigcho.teams(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK(length(name) BETWEEN 1 AND 40),
    short_name text NOT NULL CHECK(length(short_name) BETWEEN 1 AND 4),
    url text NOT NULL DEFAULT '' CHECK(length(url)<=255),
    description text NOT NULL DEFAULT '' CHECK(length(description)<=64000),
    is_open boolean NOT NULL DEFAULT true,
    default_ruleset_id smallint NOT NULL DEFAULT 0 CHECK(default_ruleset_id BETWEEN 0 AND 3),
    leader_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE RESTRICT,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE UNIQUE INDEX teams_name_unique ON zigcho.teams(lower(name));
CREATE UNIQUE INDEX teams_short_name_unique ON zigcho.teams(lower(short_name));

CREATE TABLE zigcho.team_members(
    user_id integer PRIMARY KEY REFERENCES zigcho.users(id) ON DELETE CASCADE,
    team_id integer NOT NULL REFERENCES zigcho.teams(id) ON DELETE CASCADE,
    joined_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX team_members_team_time ON zigcho.team_members(team_id,joined_at,user_id);

CREATE TABLE zigcho.team_applications(
    user_id integer PRIMARY KEY REFERENCES zigcho.users(id) ON DELETE CASCADE,
    team_id integer NOT NULL REFERENCES zigcho.teams(id) ON DELETE CASCADE,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX team_applications_team_time ON zigcho.team_applications(team_id,created_at,user_id);

CREATE TABLE zigcho.team_assets(
    team_id integer NOT NULL REFERENCES zigcho.teams(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK(kind IN('flag','header')),
    object_key text NOT NULL UNIQUE CHECK(length(object_key) BETWEEN 1 AND 200),
    content_type text NOT NULL CHECK(content_type IN('image/png','image/jpeg','image/gif')),
    etag char(64) NOT NULL,
    width integer NOT NULL CHECK(width BETWEEN 1 AND 2000),
    height integer NOT NULL CHECK(height BETWEEN 1 AND 500),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(team_id,kind)
);

CREATE TABLE zigcho.lazer_presence(
    user_id integer PRIMARY KEY REFERENCES zigcho.users(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT '' CHECK(length(status)<=80),
    detail text NOT NULL DEFAULT '' CHECK(length(detail)<=200),
    beatmap_id integer,
    ruleset_id smallint CHECK(ruleset_id IS NULL OR ruleset_id BETWEEN 0 AND 3),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE zigcho.replay_objects(
    source text NOT NULL CHECK(source IN('stable','lazer')),
    score_id bigint NOT NULL CHECK(score_id>0),
    object_key text NOT NULL UNIQUE CHECK(length(object_key) BETWEEN 1 AND 200),
    etag char(64) NOT NULL,
    object_bytes bigint NOT NULL CHECK(object_bytes>0),
    stored_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(source,score_id)
);

CREATE TABLE zigcho.lazer_reports(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    reportable_type text NOT NULL CHECK(reportable_type IN('user','message','comment')),
    reportable_id bigint NOT NULL CHECK(reportable_id>0),
    reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 64),
    comments text NOT NULL DEFAULT '' CHECK(length(comments)<=1000),
    status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    resolved_at bigint,
    resolver_id integer REFERENCES zigcho.users(id) ON DELETE SET NULL,
    UNIQUE(reporter_id,reportable_type,reportable_id)
);
CREATE INDEX lazer_reports_status_time ON zigcho.lazer_reports(status,created_at,id);

CREATE TABLE zigcho.beatmap_tag_votes(
    beatmap_id integer NOT NULL REFERENCES zigcho.beatmaps(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    tag_id smallint NOT NULL CHECK(tag_id BETWEEN 1 AND 16),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(beatmap_id,user_id,tag_id)
);
CREATE INDEX beatmap_tag_votes_map_tag ON zigcho.beatmap_tag_votes(beatmap_id,tag_id,created_at);

CREATE TABLE zigcho.profile_score_pins(
    user_id integer NOT NULL REFERENCES zigcho.users(id) ON DELETE CASCADE,
    source text NOT NULL CHECK(source IN('stable','lazer')),
    score_id bigint NOT NULL CHECK(score_id>0),
    mode smallint NOT NULL CHECK(mode BETWEEN 0 AND 3),
    rank_namespace text NOT NULL CHECK(rank_namespace IN('vanilla','relax','autopilot','scorev2','custom')),
    pinned_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(user_id,source,score_id),
    UNIQUE(source,score_id)
);
CREATE INDEX profile_score_pins_user_mode ON zigcho.profile_score_pins(user_id,mode,rank_namespace,pinned_at DESC,score_id DESC);
INSERT INTO zigcho.profile_score_pins(user_id,source,score_id,mode,rank_namespace,pinned_at)
SELECT p.user_id,'stable',p.score_id,s.mode,s.rank_namespace,p.pinned_at FROM zigcho.score_pins p JOIN zigcho.scores s ON s.id=p.score_id;

INSERT INTO zigcho.schema_migrations(version) VALUES(33);
COMMIT;
