CREATE SCHEMA IF NOT EXISTS zigcho;
SET search_path = zigcho, pg_catalog;

CREATE TABLE schema_migrations (
    version integer PRIMARY KEY,
    applied_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    safe_name text NOT NULL UNIQUE,
    password_hash bytea NOT NULL,
    password_salt bytea NOT NULL,
    email text UNIQUE,
    country char(2) NOT NULL DEFAULT 'XX',
    privileges bigint NOT NULL DEFAULT 3,
    silence_end bigint NOT NULL DEFAULT 0,
    restricted boolean NOT NULL DEFAULT false,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_login bigint,
    avatar_key smallint NOT NULL DEFAULT 1 CHECK (avatar_key IN (1, 2)),
    bio text NOT NULL DEFAULT '' CHECK (length(bio) <= 500),
    preferred_mode smallint NOT NULL DEFAULT 0 CHECK (preferred_mode BETWEEN 0 AND 3),
    profile_source text NOT NULL DEFAULT 'all' CHECK (profile_source IN ('all', 'lazer', 'scorev2')),
    profile_title text NOT NULL DEFAULT '' CHECK (length(profile_title) <= 40),
    profile_pronouns text NOT NULL DEFAULT '' CHECK (length(profile_pronouns) <= 32),
    profile_location text NOT NULL DEFAULT '' CHECK (length(profile_location) <= 60),
    profile_website text NOT NULL DEFAULT '' CHECK (length(profile_website) <= 200),
    profile_accent text NOT NULL DEFAULT 'pink' CHECK (profile_accent IN ('pink', 'violet', 'blue', 'mint', 'gold', 'red')),
    show_country boolean NOT NULL DEFAULT true,
    show_profile_stats boolean NOT NULL DEFAULT true,
    show_recent_scores boolean NOT NULL DEFAULT true,
    username_changes integer NOT NULL DEFAULT 0 CHECK(username_changes >= 0),
    username_changed_at bigint
);

CREATE TABLE user_avatars (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    object_key text NOT NULL UNIQUE CHECK (length(object_key) BETWEEN 1 AND 200),
    content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/gif')),
    etag char(64) NOT NULL,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE user_name_changes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    old_name text NOT NULL,
    new_name text NOT NULL,
    changed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX user_name_changes_user_time ON user_name_changes(user_id, changed_at DESC, id DESC);

CREATE TABLE user_banners (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    object_key text NOT NULL UNIQUE CHECK (length(object_key) BETWEEN 1 AND 200),
    content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/gif')),
    etag char(64) NOT NULL,
    width integer NOT NULL CHECK (width BETWEEN 1 AND 2000),
    height integer NOT NULL CHECK (height BETWEEN 1 AND 500),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE teams (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (length(name) BETWEEN 1 AND 40),
    short_name text NOT NULL CHECK (length(short_name) BETWEEN 1 AND 4),
    url text NOT NULL DEFAULT '' CHECK (length(url) <= 255),
    description text NOT NULL DEFAULT '' CHECK (length(description) <= 64000),
    is_open boolean NOT NULL DEFAULT true,
    default_ruleset_id smallint NOT NULL DEFAULT 0 CHECK (default_ruleset_id BETWEEN 0 AND 3),
    leader_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE UNIQUE INDEX teams_name_unique ON teams(lower(name));
CREATE UNIQUE INDEX teams_short_name_unique ON teams(lower(short_name));

CREATE TABLE team_members (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    team_id integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    joined_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX team_members_team_time ON team_members(team_id, joined_at, user_id);

CREATE TABLE team_applications (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    team_id integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX team_applications_team_time ON team_applications(team_id, created_at, user_id);

CREATE TABLE team_assets (
    team_id integer NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('flag', 'header')),
    object_key text NOT NULL UNIQUE CHECK (length(object_key) BETWEEN 1 AND 200),
    content_type text NOT NULL CHECK (content_type IN ('image/png', 'image/jpeg', 'image/gif')),
    etag char(64) NOT NULL,
    width integer NOT NULL CHECK (width BETWEEN 1 AND 2000),
    height integer NOT NULL CHECK (height BETWEEN 1 AND 500),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(team_id, kind)
);

CREATE TABLE lazer_presence (
    user_id integer PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT '' CHECK (length(status) <= 80),
    detail text NOT NULL DEFAULT '' CHECK (length(detail) <= 200),
    beatmap_id integer,
    ruleset_id smallint CHECK (ruleset_id IS NULL OR ruleset_id BETWEEN 0 AND 3),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE replay_objects (
    source text NOT NULL CHECK (source IN ('stable', 'lazer')),
    score_id bigint NOT NULL CHECK (score_id > 0),
    object_key text NOT NULL UNIQUE CHECK (length(object_key) BETWEEN 1 AND 200),
    etag char(64) NOT NULL,
    object_bytes bigint NOT NULL CHECK (object_bytes > 0),
    stored_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (source, score_id)
);

CREATE TABLE profile_score_pins (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source text NOT NULL CHECK (source IN ('stable', 'lazer')),
    score_id bigint NOT NULL CHECK (score_id > 0),
    mode smallint NOT NULL CHECK (mode BETWEEN 0 AND 3),
    rank_namespace text NOT NULL CHECK (rank_namespace IN ('vanilla', 'relax', 'autopilot', 'scorev2', 'custom')),
    pinned_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, source, score_id),
    UNIQUE (source, score_id)
);
CREATE INDEX profile_score_pins_user_mode ON profile_score_pins(user_id, mode, rank_namespace, pinned_at DESC, score_id DESC);

CREATE TABLE stats (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode smallint NOT NULL,
    ranked_score bigint NOT NULL DEFAULT 0,
    total_score bigint NOT NULL DEFAULT 0,
    pp integer NOT NULL DEFAULT 0,
    plays integer NOT NULL DEFAULT 0,
    play_time bigint NOT NULL DEFAULT 0,
    accuracy double precision NOT NULL DEFAULT 0,
    max_combo integer NOT NULL DEFAULT 0,
    total_hits bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, mode)
);

CREATE TABLE beatmaps (
    id integer PRIMARY KEY,
    set_id integer NOT NULL,
    md5 char(32) NOT NULL UNIQUE,
    artist text NOT NULL,
    title text NOT NULL,
    version text NOT NULL,
    creator text NOT NULL,
    status smallint NOT NULL DEFAULT 2,
    status_frozen boolean NOT NULL DEFAULT false,
    last_update bigint,
    total_length integer NOT NULL DEFAULT 0,
    max_combo integer NOT NULL DEFAULT 0,
    plays integer NOT NULL DEFAULT 0,
    passes integer NOT NULL DEFAULT 0,
    mode smallint NOT NULL DEFAULT 0,
    bpm double precision NOT NULL DEFAULT 0,
    cs double precision NOT NULL DEFAULT 0,
    ar double precision NOT NULL DEFAULT 0,
    od double precision NOT NULL DEFAULT 0,
    hp double precision NOT NULL DEFAULT 0,
    star_rating double precision NOT NULL DEFAULT 0,
    source text NOT NULL DEFAULT '',
    tags text NOT NULL DEFAULT '',
    osu_file bytea,
    count_circles integer NOT NULL DEFAULT 0,
    count_sliders integer NOT NULL DEFAULT 0,
    count_spinners integer NOT NULL DEFAULT 0
);
CREATE INDEX beatmaps_search ON beatmaps(artist, title, creator);

CREATE TABLE scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    map_md5 char(32) NOT NULL,
    mode smallint NOT NULL,
    mods integer NOT NULL,
    score bigint NOT NULL,
    pp double precision NOT NULL DEFAULT 0,
    star_rating double precision NOT NULL DEFAULT 0,
    accuracy double precision NOT NULL,
    max_combo integer NOT NULL,
    n300 integer NOT NULL,
    n100 integer NOT NULL,
    n50 integer NOT NULL,
    nmiss integer NOT NULL,
    ngeki integer NOT NULL,
    nkatu integer NOT NULL,
    perfect boolean NOT NULL,
    passed boolean NOT NULL,
    replay bytea,
    submitted_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    checksum text,
    rank_namespace text NOT NULL DEFAULT 'vanilla',
    best boolean NOT NULL DEFAULT false,
    time_elapsed bigint NOT NULL DEFAULT 0,
    UNIQUE (user_id, map_md5, mode, mods, score)
);
CREATE INDEX scores_leaderboard ON scores(map_md5, mode, mods, pp DESC, score DESC);
CREATE UNIQUE INDEX scores_checksum_unique ON scores(checksum) WHERE checksum IS NOT NULL;
CREATE INDEX scores_stable_board ON scores(map_md5, mode, rank_namespace, best, score DESC);

CREATE TABLE score_pins (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score_id bigint NOT NULL UNIQUE REFERENCES scores(id) ON DELETE CASCADE,
    pinned_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, score_id)
);
CREATE INDEX score_pins_user_time ON score_pins(user_id, pinned_at DESC, score_id DESC);

CREATE TABLE friends (
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    friend_id integer REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE favourites (
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    set_id integer NOT NULL,
    created_at bigint DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, set_id)
);

CREATE TABLE ratings (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    map_md5 char(32) NOT NULL REFERENCES beatmaps(md5) ON UPDATE CASCADE ON DELETE CASCADE,
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 10),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, map_md5)
);

CREATE TABLE beatmap_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id bigint NOT NULL,
    target_type text NOT NULL CHECK (target_type IN ('song','map','replay')),
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    time double precision NOT NULL,
    comment text NOT NULL CHECK (length(comment) BETWEEN 1 AND 80),
    colour char(6),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_comments_target ON beatmap_comments(target_type, target_id, id);

CREATE TABLE direct_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    to_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message text NOT NULL CHECK (length(message) BETWEEN 1 AND 2000),
    read boolean NOT NULL DEFAULT false,
    is_action boolean NOT NULL DEFAULT false,
    client_uuid text NOT NULL DEFAULT '',
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX direct_messages_unread ON direct_messages(to_id, read, created_at, id);
CREATE INDEX direct_messages_conversation ON direct_messages(to_id, from_id, read, id);
CREATE UNIQUE INDEX direct_messages_sender_uuid ON direct_messages(from_id, client_uuid) WHERE client_uuid!='';

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id integer,
    action text NOT NULL,
    target text,
    detail text,
    created_at bigint DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE anticheat_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score_id bigint REFERENCES scores(id) ON DELETE SET NULL,
    source text NOT NULL CHECK(source IN ('stable_login','stable_lastfm','stable_score')),
    module text NOT NULL CHECK(length(module) BETWEEN 1 AND 64),
    action smallint NOT NULL CHECK(action BETWEEN 0 AND 3),
    sample_weight integer NOT NULL DEFAULT 1 CHECK(sample_weight BETWEEN 1 AND 100000),
    reason integer NOT NULL,
    risk_score smallint NOT NULL CHECK(risk_score BETWEEN 0 AND 1000),
    confidence_bps integer NOT NULL CHECK(confidence_bps BETWEEN 0 AND 10000),
    evidence bigint NOT NULL DEFAULT 0 CHECK(evidence >= 0),
    decision_flags bigint NOT NULL DEFAULT 0 CHECK(decision_flags >= 0),
    rule_revision integer NOT NULL DEFAULT 0,
    objects_checked integer NOT NULL DEFAULT 0 CHECK(objects_checked >= 0),
    matched_clicks integer NOT NULL DEFAULT 0 CHECK(matched_clicks BETWEEN 0 AND objects_checked),
    mean_abs_timing_error_milli integer NOT NULL DEFAULT 0 CHECK(mean_abs_timing_error_milli >= 0),
    timing_stddev_milli integer NOT NULL DEFAULT 0 CHECK(timing_stddev_milli >= 0),
    exact_timing_bps integer NOT NULL DEFAULT 0 CHECK(exact_timing_bps BETWEEN 0 AND 10000),
    center_hits_bps integer NOT NULL DEFAULT 0 CHECK(center_hits_bps BETWEEN 0 AND 10000),
    mean_center_distance_milli integer NOT NULL DEFAULT 0 CHECK(mean_center_distance_milli >= 0),
    snap_events integer NOT NULL DEFAULT 0 CHECK(snap_events BETWEEN 0 AND objects_checked),
    replay_match_count integer NOT NULL DEFAULT 0 CHECK(replay_match_count BETWEEN 0 AND 100000),
    key_press_count integer NOT NULL DEFAULT 0 CHECK(key_press_count >= 0),
    key_hold_count integer NOT NULL DEFAULT 0 CHECK(key_hold_count BETWEEN 0 AND key_press_count),
    mean_hold_duration_milli integer NOT NULL DEFAULT 0 CHECK(mean_hold_duration_milli >= 0),
    hold_duration_stddev_milli integer NOT NULL DEFAULT 0 CHECK(hold_duration_stddev_milli >= 0),
    alternation_bps integer NOT NULL DEFAULT 0 CHECK(alternation_bps BETWEEN 0 AND 10000),
    target_distance_stddev_milli integer NOT NULL DEFAULT 0 CHECK(target_distance_stddev_milli >= 0),
    velocity_spike_count integer NOT NULL DEFAULT 0 CHECK(velocity_spike_count >= 0),
    movement_velocity_stddev_milli integer NOT NULL DEFAULT 0 CHECK(movement_velocity_stddev_milli >= 0),
    review_label text NOT NULL DEFAULT 'pending' CHECK(review_label IN ('pending','clean','uncertain','cheat','dismissed')),
    reviewer_id integer REFERENCES users(id) ON DELETE SET NULL,
    review_note text NOT NULL DEFAULT '' CHECK(length(review_note) <= 1000),
    reviewed_at bigint,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    CHECK(
        (review_label = 'pending' AND reviewer_id IS NULL AND reviewed_at IS NULL AND review_note = '') OR
        (review_label != 'pending' AND reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL AND length(review_note) BETWEEN 3 AND 1000)
    )
);
CREATE UNIQUE INDEX anticheat_observations_score ON anticheat_observations(score_id) WHERE score_id IS NOT NULL;
CREATE INDEX anticheat_observations_queue ON anticheat_observations(review_label, created_at, id);
CREATE INDEX anticheat_observations_user ON anticheat_observations(user_id, created_at DESC, id DESC);

CREATE TABLE anticheat_replay_fingerprints (
    score_id bigint PRIMARY KEY REFERENCES scores(id) ON DELETE CASCADE,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    replay_sha256 bytea NOT NULL CHECK(octet_length(replay_sha256) = 32),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX anticheat_replay_fingerprints_hash ON anticheat_replay_fingerprints(replay_sha256, user_id);
CREATE INDEX anticheat_replay_fingerprints_user ON anticheat_replay_fingerprints(user_id, created_at DESC, score_id DESC);

CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target text NOT NULL,
    message text NOT NULL,
    is_action boolean NOT NULL DEFAULT false,
    client_uuid text NOT NULL DEFAULT '' CHECK(length(client_uuid) IN (0,36)),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX chat_messages_target_time ON chat_messages(target, created_at DESC);
CREATE INDEX chat_messages_sender_time ON chat_messages(sender_id, created_at DESC);
CREATE UNIQUE INDEX chat_messages_sender_uuid ON chat_messages(sender_id, client_uuid) WHERE client_uuid!='';

CREATE TABLE lazer_channel_reads (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id smallint NOT NULL CHECK(channel_id BETWEEN 1 AND 4),
    last_read_id bigint NOT NULL DEFAULT 0,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(user_id, channel_id)
);

CREATE TABLE user_blocks (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(user_id, blocked_id),
    CHECK(user_id != blocked_id)
);

CREATE TABLE chat_channels (
    name text PRIMARY KEY,
    topic text NOT NULL,
    write_privileges bigint NOT NULL DEFAULT 1,
    locked boolean NOT NULL DEFAULT false,
    updated_by integer,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE beatmap_rank_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL,
    map_id integer NOT NULL REFERENCES beatmaps(id) ON DELETE CASCADE,
    requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active boolean NOT NULL DEFAULT true,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    resolved_at bigint
);
CREATE UNIQUE INDEX beatmap_rank_requests_active_user
    ON beatmap_rank_requests(set_id, requester_id) WHERE active;
CREATE INDEX beatmap_rank_requests_queue
    ON beatmap_rank_requests(active, created_at, set_id);

CREATE TABLE beatmap_nominations (
    set_id integer NOT NULL,
    nominator_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active boolean NOT NULL DEFAULT true,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (set_id, nominator_id)
);
CREATE INDEX beatmap_nominations_active ON beatmap_nominations(set_id, active);

CREATE TABLE beatmap_rank_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL,
    actor_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    action text NOT NULL,
    from_status smallint NOT NULL,
    to_status smallint NOT NULL,
    reason text NOT NULL,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_rank_events_set_time
    ON beatmap_rank_events(set_id, created_at DESC, id DESC);

CREATE TABLE lazer_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    beatmap_id integer NOT NULL,
    ruleset_id smallint NOT NULL,
    total_score bigint NOT NULL,
    legacy_total_score bigint,
    accuracy double precision NOT NULL,
    max_combo integer NOT NULL,
    passed boolean NOT NULL,
    rank text NOT NULL DEFAULT 'F',
    mods_json jsonb NOT NULL,
    statistics_json jsonb NOT NULL,
    maximum_statistics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    pauses_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    pp double precision NOT NULL DEFAULT 0,
    star_rating double precision NOT NULL DEFAULT 0,
    best boolean NOT NULL DEFAULT false,
    rank_namespace text NOT NULL,
    client_version text,
    replay bytea,
    submitted_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX lazer_scores_board ON lazer_scores(beatmap_id, ruleset_id, rank_namespace, total_score DESC);
CREATE INDEX lazer_scores_user_best ON lazer_scores(user_id, ruleset_id, rank_namespace, beatmap_id, best);

CREATE TABLE lazer_score_tokens (
    id bigint PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    beatmap_id integer NOT NULL REFERENCES beatmaps(id) ON DELETE CASCADE,
    beatmap_hash char(32) NOT NULL,
    ruleset_id smallint NOT NULL CHECK(ruleset_id BETWEEN 0 AND 3),
    version_hash char(32) NOT NULL,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    expires_at bigint NOT NULL,
    consumed_at bigint,
    score_id bigint REFERENCES lazer_scores(id) ON DELETE SET NULL
);
CREATE INDEX lazer_score_tokens_user_expiry ON lazer_score_tokens(user_id, expires_at DESC);

CREATE TABLE user_achievements (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    achievement_id smallint NOT NULL CHECK(achievement_id > 0),
    score_source text NOT NULL CHECK(score_source IN ('stable','lazer')),
    score_id bigint NOT NULL CHECK(score_id > 0),
    achieved_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(user_id, achievement_id)
);
CREATE INDEX user_achievements_score ON user_achievements(score_source, score_id);

CREATE TABLE custom_mods (
    acronym text PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    ranked boolean NOT NULL DEFAULT true,
    score_multiplier double precision NOT NULL DEFAULT 1,
    settings_schema jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE oauth_tokens (
    token_hash bytea PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scopes text NOT NULL,
    client_id integer,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    expires_at bigint NOT NULL,
    revoked_at bigint,
    last_used_at bigint
);
CREATE INDEX oauth_tokens_user ON oauth_tokens(user_id, expires_at);

CREATE TABLE beatmap_archives (
    set_id integer PRIMARY KEY,
    sha256 char(64) NOT NULL,
    osz_file bytea,
    object_bytes bigint NOT NULL DEFAULT 0 CHECK(object_bytes >= 0),
    imported_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_accessed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_archives_lru ON beatmap_archives(last_accessed_at, imported_at, set_id);

CREATE TABLE lazer_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentable_type text NOT NULL CHECK(commentable_type IN ('beatmapset','build','news_post')),
    commentable_id bigint NOT NULL CHECK(commentable_id > 0),
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id bigint REFERENCES lazer_comments(id) ON DELETE CASCADE,
    message text NOT NULL CHECK(length(message) BETWEEN 0 AND 1000),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    deleted_at bigint,
    CHECK(parent_id IS NULL OR parent_id != id)
);
CREATE INDEX lazer_comments_target ON lazer_comments(commentable_type,commentable_id,parent_id,created_at,id);
CREATE TABLE lazer_comment_votes (comment_id bigint NOT NULL REFERENCES lazer_comments(id) ON DELETE CASCADE,user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(comment_id,user_id));
CREATE TABLE lazer_comment_reports (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,comment_id bigint NOT NULL REFERENCES lazer_comments(id) ON DELETE CASCADE,reporter_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 64),comments text NOT NULL CHECK(length(comments)<=1000),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint));
CREATE UNIQUE INDEX lazer_comment_reports_once ON lazer_comment_reports(comment_id,reporter_id);
CREATE TABLE lazer_reports (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reporter_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,reportable_type text NOT NULL CHECK(reportable_type IN('user','message','comment')),reportable_id bigint NOT NULL CHECK(reportable_id>0),reason text NOT NULL CHECK(length(reason) BETWEEN 1 AND 64),comments text NOT NULL DEFAULT '' CHECK(length(comments)<=1000),status text NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),resolved_at bigint,resolver_id integer REFERENCES users(id) ON DELETE SET NULL,UNIQUE(reporter_id,reportable_type,reportable_id));
CREATE INDEX lazer_reports_status_time ON lazer_reports(status,created_at,id);
CREATE TABLE beatmap_tag_votes (beatmap_id integer NOT NULL REFERENCES beatmaps(id) ON DELETE CASCADE,user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,tag_id smallint NOT NULL CHECK(tag_id BETWEEN 1 AND 16),created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),PRIMARY KEY(beatmap_id,user_id,tag_id));
CREATE INDEX beatmap_tag_votes_map_tag ON beatmap_tag_votes(beatmap_id,tag_id,created_at);

CREATE TABLE beatmap_hydration_failures (
    md5 char(32) PRIMARY KEY,
    set_id integer NOT NULL,
    attempts smallint NOT NULL DEFAULT 1 CHECK(attempts BETWEEN 1 AND 32),
    next_retry_at bigint NOT NULL,
    last_error text NOT NULL,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_hydration_retry ON beatmap_hydration_failures(next_retry_at, updated_at);

CREATE TABLE client_hardware (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    osu_path_md5 char(32) NOT NULL,
    adapters_md5 char(32) NOT NULL,
    uninstall_md5 char(32) NOT NULL,
    disk_signature_md5 char(32) NOT NULL,
    client_version text NOT NULL,
    running_under_wine boolean NOT NULL,
    first_seen bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_seen bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    occurrences integer NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, osu_path_md5, adapters_md5, uninstall_md5, disk_signature_md5),
    CHECK (length(osu_path_md5) = 32),
    CHECK (length(adapters_md5) = 32),
    CHECK (length(uninstall_md5) = 32),
    CHECK (length(disk_signature_md5) = 32)
);
CREATE INDEX client_hardware_exact_match ON client_hardware(adapters_md5, uninstall_md5, disk_signature_md5, user_id);

CREATE TABLE moderation_appeals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK(kind IN ('restriction','hwid')),
    message text NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','denied')),
    reviewer_id integer REFERENCES users(id) ON DELETE SET NULL,
    resolution text,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    resolved_at bigint
);
CREATE UNIQUE INDEX moderation_appeals_one_open ON moderation_appeals(user_id, kind) WHERE status='open';
CREATE INDEX moderation_appeals_queue ON moderation_appeals(status, created_at, id);

CREATE TABLE screenshots (
    token char(8) PRIMARY KEY,
    extension text NOT NULL CHECK(extension IN ('jpeg','png')),
    uploader_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    image bytea NOT NULL CHECK(octet_length(image) <= 4194304),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX screenshots_uploader_time ON screenshots(uploader_id, created_at DESC);

CREATE TABLE beatmap_media (
    set_id integer NOT NULL,
    kind text NOT NULL CHECK(kind IN (
        'cover','cover_2x','card','card_2x','list','list_2x',
        'slimcover','slimcover_2x','thumb','thumb_large','preview'
    )),
    content_type text NOT NULL CHECK(content_type IN ('image/jpeg','audio/ogg','audio/mpeg')),
    sha256 char(64) NOT NULL,
    data bytea CHECK(data IS NULL OR octet_length(data) BETWEEN 1 AND 4194304),
    fetched_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_accessed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY(set_id, kind)
);
CREATE INDEX beatmap_media_lru ON beatmap_media(last_accessed_at, fetched_at, set_id, kind);

INSERT INTO custom_mods(acronym,name,description,ranked,score_multiplier,settings_schema)
VALUES('RX','Relax','Server-side cursor relax; clicks are generated automatically.',true,0,'{"type":"object","additionalProperties":false}'::jsonb);

INSERT INTO users(id,name,safe_name,password_hash,password_salt,country,privileges,restricted,avatar_key)
VALUES(3,'kai','kai',''::bytea,'system'::bytea,'XX',24579,false,1);
INSERT INTO stats(user_id,mode) VALUES(3,0),(3,1),(3,2),(3,3),(3,4),(3,5),(3,6),(3,8);
SELECT setval(pg_get_serial_sequence('users','id'),3,true);

INSERT INTO chat_channels(name,topic,write_privileges)
VALUES('#osu','general chat',1),('#announce','updates',8192),('#lobby','multiplayer lobby',1),('#lazer','lazer chat',1);

INSERT INTO schema_migrations(version) VALUES (33);
