CREATE SCHEMA IF NOT EXISTS zigcho;
SET search_path = zigcho, pg_catalog;

CREATE TABLE schema_migrations (
    version integer PRIMARY KEY,
    applied_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    safe_name text NOT NULL UNIQUE,
    password_hash bytea NOT NULL,
    password_salt bytea NOT NULL,
    email text UNIQUE,
    country char(2) NOT NULL DEFAULT 'XX',
    privileges bigint NOT NULL DEFAULT 3,
    silence_end bigint NOT NULL DEFAULT 0,
    restricted boolean NOT NULL DEFAULT false,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_login bigint,
    avatar_key smallint NOT NULL DEFAULT 1 CHECK (avatar_key IN (1, 2))
);

CREATE TABLE stats (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode smallint NOT NULL,
    ranked_score bigint NOT NULL DEFAULT 0,
    total_score bigint NOT NULL DEFAULT 0,
    pp integer NOT NULL DEFAULT 0,
    plays integer NOT NULL DEFAULT 0,
    play_time bigint NOT NULL DEFAULT 0,
    accuracy double precision NOT NULL DEFAULT 0,
    max_combo integer NOT NULL DEFAULT 0,
    total_hits bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, mode)
);

CREATE TABLE beatmaps (
    id integer PRIMARY KEY,
    set_id integer NOT NULL,
    md5 char(32) NOT NULL UNIQUE,
    artist text NOT NULL,
    title text NOT NULL,
    version text NOT NULL,
    creator text NOT NULL,
    status smallint NOT NULL DEFAULT 2,
    status_frozen boolean NOT NULL DEFAULT false,
    last_update bigint,
    total_length integer NOT NULL DEFAULT 0,
    max_combo integer NOT NULL DEFAULT 0,
    plays integer NOT NULL DEFAULT 0,
    passes integer NOT NULL DEFAULT 0,
    mode smallint NOT NULL DEFAULT 0,
    bpm double precision NOT NULL DEFAULT 0,
    cs double precision NOT NULL DEFAULT 0,
    ar double precision NOT NULL DEFAULT 0,
    od double precision NOT NULL DEFAULT 0,
    hp double precision NOT NULL DEFAULT 0,
    star_rating double precision NOT NULL DEFAULT 0,
    source text NOT NULL DEFAULT '',
    tags text NOT NULL DEFAULT '',
    osu_file bytea,
    count_circles integer NOT NULL DEFAULT 0,
    count_sliders integer NOT NULL DEFAULT 0,
    count_spinners integer NOT NULL DEFAULT 0
);
CREATE INDEX beatmaps_search ON beatmaps(artist, title, creator);

CREATE TABLE scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    map_md5 char(32) NOT NULL,
    mode smallint NOT NULL,
    mods integer NOT NULL,
    score bigint NOT NULL,
    pp double precision NOT NULL DEFAULT 0,
    accuracy double precision NOT NULL,
    max_combo integer NOT NULL,
    n300 integer NOT NULL,
    n100 integer NOT NULL,
    n50 integer NOT NULL,
    nmiss integer NOT NULL,
    ngeki integer NOT NULL,
    nkatu integer NOT NULL,
    perfect boolean NOT NULL,
    passed boolean NOT NULL,
    replay bytea,
    submitted_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    checksum text,
    rank_namespace text NOT NULL DEFAULT 'vanilla',
    best boolean NOT NULL DEFAULT false,
    time_elapsed bigint NOT NULL DEFAULT 0,
    UNIQUE (user_id, map_md5, mode, mods, score)
);
CREATE INDEX scores_leaderboard ON scores(map_md5, mode, mods, pp DESC, score DESC);
CREATE UNIQUE INDEX scores_checksum_unique ON scores(checksum) WHERE checksum IS NOT NULL;
CREATE INDEX scores_stable_board ON scores(map_md5, mode, rank_namespace, best, score DESC);

CREATE TABLE score_pins (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score_id bigint NOT NULL UNIQUE REFERENCES scores(id) ON DELETE CASCADE,
    pinned_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, score_id)
);
CREATE INDEX score_pins_user_time ON score_pins(user_id, pinned_at DESC, score_id DESC);

CREATE TABLE friends (
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    friend_id integer REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE favourites (
    user_id integer REFERENCES users(id) ON DELETE CASCADE,
    set_id integer NOT NULL,
    created_at bigint DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, set_id)
);

CREATE TABLE ratings (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    map_md5 char(32) NOT NULL REFERENCES beatmaps(md5) ON UPDATE CASCADE ON DELETE CASCADE,
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 10),
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (user_id, map_md5)
);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id integer,
    action text NOT NULL,
    target text,
    detail text,
    created_at bigint DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target text NOT NULL,
    message text NOT NULL,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX chat_messages_target_time ON chat_messages(target, created_at DESC);
CREATE INDEX chat_messages_sender_time ON chat_messages(sender_id, created_at DESC);

CREATE TABLE chat_channels (
    name text PRIMARY KEY,
    topic text NOT NULL,
    write_privileges bigint NOT NULL DEFAULT 1,
    locked boolean NOT NULL DEFAULT false,
    updated_by integer,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);

CREATE TABLE beatmap_rank_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL,
    map_id integer NOT NULL REFERENCES beatmaps(id) ON DELETE CASCADE,
    requester_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active boolean NOT NULL DEFAULT true,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    resolved_at bigint
);
CREATE UNIQUE INDEX beatmap_rank_requests_active_user
    ON beatmap_rank_requests(set_id, requester_id) WHERE active;
CREATE INDEX beatmap_rank_requests_queue
    ON beatmap_rank_requests(active, created_at, set_id);

CREATE TABLE beatmap_nominations (
    set_id integer NOT NULL,
    nominator_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    active boolean NOT NULL DEFAULT true,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    PRIMARY KEY (set_id, nominator_id)
);
CREATE INDEX beatmap_nominations_active ON beatmap_nominations(set_id, active);

CREATE TABLE beatmap_rank_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id integer NOT NULL,
    actor_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    action text NOT NULL,
    from_status smallint NOT NULL,
    to_status smallint NOT NULL,
    reason text NOT NULL,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_rank_events_set_time
    ON beatmap_rank_events(set_id, created_at DESC, id DESC);

CREATE TABLE lazer_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    beatmap_id integer NOT NULL,
    ruleset_id smallint NOT NULL,
    total_score bigint NOT NULL,
    legacy_total_score bigint,
    accuracy double precision NOT NULL,
    max_combo integer NOT NULL,
    passed boolean NOT NULL,
    mods_json jsonb NOT NULL,
    statistics_json jsonb NOT NULL,
    rank_namespace text NOT NULL,
    client_version text,
    replay bytea,
    submitted_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX lazer_scores_board ON lazer_scores(beatmap_id, ruleset_id, rank_namespace, total_score DESC);

CREATE TABLE custom_mods (
    acronym text PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    ranked boolean NOT NULL DEFAULT false,
    score_multiplier double precision NOT NULL DEFAULT 1,
    settings_schema jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE oauth_tokens (
    token_hash bytea PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scopes text NOT NULL,
    client_id integer,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    expires_at bigint NOT NULL,
    revoked_at bigint,
    last_used_at bigint
);
CREATE INDEX oauth_tokens_user ON oauth_tokens(user_id, expires_at);

CREATE TABLE beatmap_archives (
    set_id integer PRIMARY KEY,
    sha256 char(64) NOT NULL,
    osz_file bytea NOT NULL,
    imported_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_accessed_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_archives_lru ON beatmap_archives(last_accessed_at, imported_at, set_id);

CREATE TABLE beatmap_hydration_failures (
    md5 char(32) PRIMARY KEY,
    set_id integer NOT NULL,
    attempts smallint NOT NULL DEFAULT 1 CHECK(attempts BETWEEN 1 AND 32),
    next_retry_at bigint NOT NULL,
    last_error text NOT NULL,
    updated_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint)
);
CREATE INDEX beatmap_hydration_retry ON beatmap_hydration_failures(next_retry_at, updated_at);

CREATE TABLE client_hardware (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    osu_path_md5 char(32) NOT NULL,
    adapters_md5 char(32) NOT NULL,
    uninstall_md5 char(32) NOT NULL,
    disk_signature_md5 char(32) NOT NULL,
    client_version text NOT NULL,
    running_under_wine boolean NOT NULL,
    first_seen bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    last_seen bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    occurrences integer NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, osu_path_md5, adapters_md5, uninstall_md5, disk_signature_md5),
    CHECK (length(osu_path_md5) = 32),
    CHECK (length(adapters_md5) = 32),
    CHECK (length(uninstall_md5) = 32),
    CHECK (length(disk_signature_md5) = 32)
);
CREATE INDEX client_hardware_exact_match ON client_hardware(adapters_md5, uninstall_md5, disk_signature_md5, user_id);

CREATE TABLE moderation_appeals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK(kind IN ('restriction','hwid')),
    message text NOT NULL,
    status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','accepted','denied')),
    reviewer_id integer REFERENCES users(id) ON DELETE SET NULL,
    resolution text,
    created_at bigint NOT NULL DEFAULT (extract(epoch FROM clock_timestamp())::bigint),
    resolved_at bigint
);
CREATE UNIQUE INDEX moderation_appeals_one_open ON moderation_appeals(user_id, kind) WHERE status='open';
CREATE INDEX moderation_appeals_queue ON moderation_appeals(status, created_at, id);

INSERT INTO schema_migrations(version) VALUES (17);
